# Generated by Django 4.0.3 on 2022-04-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='Ingredientes',
            new_name='ingredientes',
        ),
    ]
